import {mkdtemp,realpath,mkdir,writeFile,rm} from 'node:fs/promises';
import os from 'node:os';import path from 'node:path';import {createHash} from 'node:crypto';
import {digestValue} from '../../dist/src/core/models.js';
export const root=process.cwd();
export async function temporary(t){const p=await realpath(await mkdtemp(path.join(os.tmpdir(),'evaldock-contract-')));t.after(()=>rm(p,{recursive:true,force:true}));return p;}
export async function json(file,value){await mkdir(path.dirname(file),{recursive:true});await writeFile(file,JSON.stringify(value));}
export function trace(entries=[]){const value={schema:'evaldock.all-trace/v1',traceId:'trace.contract',scope:{targetId:'agent.contract',targetSnapshotId:'snapshot.contract',runId:'run.contract',caseId:'case.contract',attemptId:'attempt.contract'},createdAt:'2026-09-16T00:00:00Z',producerVersion:'contract',entries,sources:[],coverage:[],artifacts:[],integrity:[]};return {...value,contentDigest:digestValue(value)};}
export function judgeInput(allTrace=trace()){const label={schema:'evaldock.label/v2',version:'1',labelId:'label.contract/v1',title:'Contract',scoringStandard:{scoring_scale:{min:0,max:10}},judge:{modelRole:'judge',instructions:['Assess supported evidence']}};return {label:{...label,contentDigest:digestValue(label)},case:{caseId:'case.contract',task:'Task',grading:{reference:{rubric:'Correct answer'}},contentDigest:digestValue({case:'contract'})},allTrace};}
export async function question(base,n=1){const dir=path.join(base,'example','question-'+n);const content='public input '+n;await mkdir(path.join(dir,'input'),{recursive:true});await writeFile(path.join(dir,'input/data.txt'),content);await json(path.join(dir,'private/final.json'),{answer:'private answer',rubric:'Match reference'});
const q={schema:'evaldock.question/v1',version:'1',id:'example-'+n,title:'Example '+n,task:{instructions:'Read the input'},environment:{platform:'portable',timeoutSeconds:60,allowedEdits:['output/**']},inputs:[{source:'input/data.txt',destination:'input/data.txt',sha256:createHash('sha256').update(content).digest('hex')}],capabilityLabels:['contract'],grading:{weight:n}};await json(path.join(dir,'question.json'),q);return {dir,q};}
