import {test} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,readFile,stat,rm} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {parseEnv} from 'node:util';
import {ModelSettings} from './model-settings.mjs';
async function fixture(t){const dir=await mkdtemp(path.join(os.tmpdir(),'evaldock-model-settings-'));t.after(()=>rm(dir,{recursive:true,force:true}));const file=path.join(dir,'models.env');const old='test-old-credential';const controllers=[{env:{DEEPSEEK_API_KEY:'test-agent-only',EVALDOCK_PLANNER_API_KEY:old,EVALDOCK_JUDGE_API_KEY:old},jobs:{environment:{},secrets:[old]},cacheUntil:999}];return {dir,file,controllers,settings:new ModelSettings({controllers,file})};}
test('keys stay server-side; save reaches every future job and preserves timeout',async t=>{const {file,controllers,settings}=await fixture(t);await writeFile(file,'# retained\nEVALDOCK_JUDGE_TIMEOUT_MS=240000\n');const out=await settings.save({planner:{apiKey:'test-new-credential',model:'model-new',endpoint:'https://example.com/v1/chat/completions'},reusePlannerForJudge:true});assert.ok(!JSON.stringify(out).includes('credential'));assert.equal(out.judge.keyConfigured,true);const env=parseEnv(await readFile(file,'utf8'));assert.equal(env.EVALDOCK_JUDGE_TIMEOUT_MS,'240000');assert.equal(env.EVALDOCK_JUDGE_API_KEY,'test-new-credential');assert.equal((await stat(file)).mode&0o777,0o600);assert.equal(controllers[0].jobs.environment.EVALDOCK_JUDGE_MODEL,'model-new');assert.equal(controllers[0].env.DEEPSEEK_API_KEY,'test-agent-only');assert.ok(controllers[0].jobs.secrets.includes('test-old-credential'));assert.ok(controllers[0].jobs.secrets.includes('test-new-credential'));assert.equal(controllers[0].cacheUntil,0);});
test('blank keys preserve saved value; restart reloads saved settings',async t=>{const {settings,controllers,file}=await fixture(t);await settings.save({planner:{apiKey:'test-persisted'}});await settings.save({planner:{apiKey:'',model:'changed'}});assert.equal(parseEnv(await readFile(file,'utf8')).EVALDOCK_PLANNER_API_KEY,'test-persisted');controllers[0].env.EVALDOCK_PLANNER_API_KEY='inherited-old';await new ModelSettings({controllers,file}).init();assert.equal(controllers[0].env.EVALDOCK_PLANNER_API_KEY,'test-persisted');});
test('invalid input cannot overwrite saved credentials',async t=>{const {settings,file}=await fixture(t);await settings.save({});const before=await readFile(file,'utf8');for(const input of [{planner:{apiKey:'bad\nINJECT=x'}},{planner:{endpoint:'https://user:password@example.com/chat/completions'}},{planner:{endpoint:'http://example.com/chat/completions'}},{planner:{extra:'x'}},{judge:[]},{reusePlannerForJudge:'yes'}])await assert.rejects(settings.save(input));assert.equal(await readFile(file,'utf8'),before);});
test('a clean installation requires user keys and exposes defaults only',async t=>{const {file}=await fixture(t);const settings=new ModelSettings({file,controllers:[{env:{},jobs:{environment:{},secrets:[]}}]});const meta=await settings.get();assert.equal(meta.planner.keyConfigured,false);await assert.rejects(settings.save({planner:{model:'x'}}),/API Key/);await settings.save({planner:{apiKey:'test-user-key'},reusePlannerForJudge:true});assert.equal((await settings.get()).judge.keyConfigured,true);});
