export const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const agentNames={dsh:'DSH',pi:'Pi',openclaw:'OpenClaw',hermes:'Hermes',workbuddy:'WorkBuddy',qwenwork:'千问办公',doubaowork:'豆包办公',langgraph:'LangGraph'};
export const isActive=j=>['STARTING','RUNNING','CANCELLING'].includes(j.state);
const states={STARTING:'准备中',RUNNING:'评测中',CANCELLING:'取消中',CANCELLED:'已取消',SUCCEEDED:'已完成',COMPLETED:'已完成',FAILED:'失败',INTERRUPTED:'已中断'};
const phases={QUEUED:'等待执行',PREPARING:'准备中',EXECUTING:'执行中',COLLECTING:'采集证据',JUDGING:'评分中',REPORTING:'生成报告',COMPLETED:'已完成',FAILED:'失败',CANCELLED:'已取消',NOT_FINISHED:'未完成',running:'执行中',done:'已完成',error:'异常'};
const date=value=>value&&Number.isFinite(Date.parse(value))?new Date(value).toLocaleString('zh-CN',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}):'—';
const heading=(title,copy,action='')=>`<div class="page-heading"><div><h1>${title}</h1><p>${copy}</p></div>${action}</div>`;
const start='<button class="primary" data-start>＋ 开始评测</button>';
const empty=(title,copy,action='')=>`<div class="empty"><span class="empty-symbol">◇</span><h3>${title}</h3><p>${copy}</p>${action}</div>`;
const stat=(label,value,copy='')=>`<div class="stat"><span>${label}</span><strong>${value}</strong>${copy?`<small>${copy}</small>`:''}</div>`;
const jobName=j=>j.targetName||agentNames[j.agentKind]||j.targetId||'Agent';
const tag=j=>`<span class="status-tag ${isActive(j)?'running':j.state==='SUCCEEDED'?'done':'neutral'}">${esc(states[j.state]||j.state)}</span>`;
export function reportHref(value){return typeof value==='string'&&/^reports\/[a-zA-Z0-9._-]+\/[^/]+\/(?:cases\/[a-zA-Z0-9._-]+\/)?report\.html$/.test(value)&&!value.split('/').some(x=>x==='..'||x==='.')?'/'+value.split('/').map(encodeURIComponent).join('/'):null;}
export function filterJobs(jobs,query='',filter='all'){
 return jobs.filter(j=>(filter==='all'||filter==='active'&&isActive(j)||filter==='done'&&j.state==='SUCCEEDED'||filter==='issues'&&['FAILED','INTERRUPTED','CANCELLED'].includes(j.state))&&[jobName(j),j.runId,j.id].join(' ').toLowerCase().includes(query.trim().toLowerCase()));
}
function progress(j){const p=j.progress??{},total=Number.isFinite(p.total)&&p.total>0?p.total:0,ended=Math.max(0,p.ended??0);return `<div class="run-progress"><progress max="${total||1}" value="${Math.min(total,ended)}" aria-label="已结束题目"></progress><small>${esc(p.label|| (isActive(j)?'正在准备评测':'评测已结束'))} · ${total?`${ended} / ${total} 题`:'题量待确认'}</small></div>`;}
function jobRow(j){return `<div class="record-row"><div><strong>${esc(jobName(j))}</strong><small>${date(j.createdAt)} · ${esc(j.evaluationConfig?.mode==='FULL'?'完整流程':'结果评测')}</small></div><div>${tag(j)}${progress(j)}</div><button data-run-detail="${esc(j.id)}">查看详情 →</button></div>`;}
export function renderHome({summary,catalog,settings,discovery}){
 const jobs=summary.jobs,active=jobs.filter(isActive),ready=summary.agents.flatMap(a=>a.targets).filter(t=>t.evaluationReady).length,count=catalog.datasets.reduce((n,d)=>n+d.cases.length,0);
 const recent=jobs.filter(j=>!isActive(j)).slice(0,3);
 return `<section class="home-intro home-intro-single"><div class="intro-copy"><h1>Agent 评测概览</h1><p>选择已接入的 Agent，运行真实任务，查看交付文件、执行过程与评分报告。</p><div class="intro-actions"><button class="primary" data-start>开始评测 <span>→</span></button><a href="#datasets">浏览测试集 ↗</a></div></div></section><div class="home-metrics"><a href="#agents"><strong>${ready}</strong><span>就绪 Agent</span><b>查看 Agent →</b></a><a href="#datasets"><strong>${count}</strong><span>测试题</span><b>浏览题库 →</b></a><a href="#reports"><strong>${jobs.length}</strong><span>评测记录</span><b>查看记录 →</b></a></div>${active.length?`<div class="section-heading"><h2>进行中 <span class="count-label">${active.length}</span></h2></div>${active.map(jobRow).join('')}`:''}<div class="section-heading"><h2>最近评测</h2><a href="#reports">全部记录 →</a></div>${recent.length?recent.map(j=>`<article class="home-record"><div class="record-emblem">${j.state==='SUCCEEDED'?'✓':'!'}</div><div class="home-record-title"><strong>${esc(jobName(j))}</strong><small>${date(j.createdAt)} · ${j.progress?.total??'—'} 道题</small></div>${tag(j)}<button data-run-detail="${esc(j.id)}">查看结果 →</button></article>`).join(''):`<div class="home-first"><h3>暂无评测记录</h3></div>`}`;
}
export function friendlyMessage(message){
 const value=String(message??'');
 const translations={AGENT_CLI_INTERFACE_UNAVAILABLE:'无法检查 Agent 的命令行接口，请检查可执行文件与运行环境。',AGENT_CLI_INTERFACE_CHANGED:'Agent 命令行缺少评测需要的参数，暂时无法运行。',LANGGRAPH_INTERFACE_UNAVAILABLE:'Graph 无法加载或缺少 stream / astream 接口，请检查入口与运行环境。',AGENT_MODEL_KEY_MISSING:'请配置被测 Agent 使用的模型密钥。',PI_STARTUP_FAILED:'Pi 未能通过 RPC 就绪检查，请检查运行环境与扩展。',PI_EXTENSION_CONFLICT:'Pi 扩展存在工具或参数冲突，请调整扩展配置。',PI_EXTENSION_LOAD_FAILED:'Pi 扩展加载失败，请检查扩展配置。',WORKBUDDY_NOT_CONNECTED:'尚未连接 WorkBuddy，请在「我的 Agent」启动连接。',WORKBUDDY_LOGIN_REQUIRED:'请打开 WorkBuddy 完成登录后重试。',WORKBUDDY_INTERFACE_CHANGED:'WorkBuddy 调用接口不可用，需要检查适配。',WORKBUDDY_EVENT_TRANSPORT_UNAVAILABLE:'WorkBuddy 事件传输接口不可用，暂时无法采集评测过程。',AGENT_VERSION_UNVERIFIED:'这是旧版的版本检查结果，请刷新状态以重新检查接口。',WORKBUDDY_VERSION_UNVERIFIED:'这是旧版的版本检查结果，请刷新状态以重新检查接口。',AGENT_INTERFACE_CHANGED:'Agent 调用或事件接口不可用，需要检查适配。',AGENT_APP_ID_MISMATCH:'安装的应用标识与目标 Agent 不符。',AGENT_LOCAL_RUNTIME_UNAVAILABLE:'Agent 的本机执行环境尚未就绪。',AGENT_INSPECTION_FAILED:'Agent 接口检查失败，请重新检查连接。',AGENT_RPC_REJECTED:'Agent 接口调用失败，请检查连接与运行状态。',AGENT_NOT_CONNECTED:'还没有连接到助手。请到「我的 Agent」点击「启动连接」。',AGENT_LOGIN_REQUIRED:'助手需要先登录。请打开对应应用完成登录，再回来继续。',AGENT_WINDOW_NOT_READY:'助手正在启动，请稍等片刻后重试。',AGENT_NOT_READY:'助手还没准备好。请到「我的 Agent」检查连接和登录状态。'};
 for(const [code,text] of Object.entries(translations))if(value.includes(code))return text;
 return /^[A-Z][A-Z0-9_]+$/.test(value)?'这次操作没有完成，请稍后重试。具体原因可展开下方详情查看。':value;
}
export function selectedItems(catalog,selection){return catalog.datasets.flatMap(d=>{const indices=d.cases.filter(c=>selection.get(d.id)?.has(c.index)).map(c=>c.index);return indices.length?[{datasetId:d.id,caseIndices:indices}]:[];});}
export function selectionCount(catalog,selection){return selectedItems(catalog,selection).reduce((n,d)=>n+d.caseIndices.length,0);}
const labelName=id=>({'label.artifact-delivery/v1':'文件交付','label.efficiency-cost/v1':'成本效率'}[id]||id.replace(/^label\./,'').replace(/\/v\d+$/,''));
export function renderDatasets({catalog,ui}){
 const count=selectionCount(catalog,ui.selection),selected=catalog.datasets.find(d=>d.id===ui.datasetId);
 const action='<button data-import>＋ 导入题库</button>';
 const selectionBar=`<div class="selection-bar"><span>已选 <strong>${count}</strong> 题</span><div><button data-clear-selection ${count?'':'disabled'}>清空选择</button> <button class="primary" data-start-selection ${count?'':'disabled'}>评测所选题目 →</button></div></div>`;
 if(selected)return `<button class="back-link" data-datasets-back>← 全部测试集</button>`+heading(esc(selected.name),`${selected.cases.length} 题 · ${esc(selected.id.split('/').at(-1))} · 已在本地`)+`<p class="dataset-description">${esc(selected.description)}</p><div class="dataset-detail-toolbar"><label><input type="checkbox" data-select-dataset="${esc(selected.id)}" ${selected.cases.every(c=>ui.selection.get(selected.id)?.has(c.index))?'checked':''}> 全选本测试集</label><span class="muted">展开题目查看任务要求</span></div><div class="case-picker">${selected.cases.map(c=>`<article class="case-pick-row"><label><input type="checkbox" data-select-case="${esc(selected.id)}" data-index="${c.index}" ${ui.selection.get(selected.id)?.has(c.index)?'checked':''}><strong>${esc(c.title)}</strong></label><div class="case-meta">${esc(c.version?'版本 '+c.version:c.id)}${c.timeoutSeconds?' · 最长 '+c.timeoutSeconds+' 秒':''}</div><details data-preserve="case-${esc(selected.id)}-${c.index}"><summary>查看任务要求</summary><p class="task-preview">${esc(c.instructions||'题目内容暂不可用，请重新加载服务。')}</p><p class="muted">${c.dependencies?.length?'声明依赖：'+c.dependencies.map(esc).join('、'):'未声明额外依赖'} · 实际运行条件在执行前检查</p></details></article>`).join('')}</div>`+selectionBar;
 const query=ui.datasetQuery.trim().toLowerCase(),visible=catalog.datasets.filter(d=>[d.name,d.description,d.id,...d.cases.map(c=>c.title)].join(' ').toLowerCase().includes(query));
 return heading('测试集','浏览本地题库，选择要交给 Agent 的真实任务。',action)+`<div class="library-summary"><span><strong>${catalog.datasets.length}</strong> 个测试集</span><span><strong>${catalog.datasets.reduce((n,d)=>n+d.cases.length,0)}</strong> 道题目</span><span class="muted">本地题库 · 可离线浏览</span></div><div class="page-toolbar"><input id="dataset-search" type="search" placeholder="搜索测试集或题目" aria-label="搜索测试集或题目" value="${esc(ui.datasetQuery)}"><span class="muted">${visible.length} 个结果</span></div><div class="dataset-grid">${visible.map(d=>`<article class="dataset-card"><div class="dataset-card-head"><span class="dataset-symbol">▦</span><span class="pill ready">已在本地</span></div><h3>${esc(d.name)}</h3><p>${esc(d.description)}</p><div class="label-chips">${(d.labelIds??[]).map(id=>`<span>${esc(labelName(id))}</span>`).join('')}</div><div class="dataset-card-foot"><span>${d.cases.length} 题 · ${esc(d.id.split('/').at(-1))}${ui.selection.get(d.id)?.size?' · 已选 '+ui.selection.get(d.id).size:''}</span><button data-dataset-detail="${esc(d.id)}">选择题目 →</button></div></article>`).join('')}</div>${!visible.length?empty(query?'没有匹配的测试集':'还没有本地题库',query?'试试其他名称或清空搜索。':'导入包含 catalog.md 的题库文件夹，或使用内置演示题。'):''}<p class="library-note">导入完整题库会切换当前题库并保留旧版本。在线浏览与按需下载尚未接入。</p>`+selectionBar;
}
export function renderReports({summary,ui}){
 const j=summary.jobs.find(j=>j.id===ui.jobId);
 if(j)return renderRun(j,summary.runs.find(r=>r.agentId===j.targetId&&r.run.id===j.runId));
 const jobs=filterJobs(summary.jobs,ui.reportQuery,ui.reportFilter),counts={all:summary.jobs.length,active:summary.jobs.filter(isActive).length,done:summary.jobs.filter(j=>j.state==='SUCCEEDED').length,issues:summary.jobs.filter(j=>['FAILED','CANCELLED','INTERRUPTED'].includes(j.state)).length};
 return heading('评测记录','跟踪执行进度，查看每一题的交付和评分依据。','<button data-refresh-records>↻ 刷新记录</button>')+`<div class="page-toolbar reports-toolbar"><div class="filter-tabs">${Object.entries({all:'全部',active:'进行中',done:'已完成',issues:'异常 / 取消'}).map(([key,label])=>`<button data-report-filter="${key}" class="${ui.reportFilter===key?'selected':''}" aria-pressed="${ui.reportFilter===key}">${label} <span>${counts[key]}</span></button>`).join('')}</div><input id="report-search" type="search" placeholder="搜索 Agent 或运行编号" aria-label="搜索评测记录" value="${esc(ui.reportQuery)}"></div>${jobs.length?`<div class="record-list">${jobs.map(jobRow).join('')}</div>`:empty(summary.jobs.length?'没有符合条件的记录':'第一份报告，从一次评测开始',summary.jobs.length?'更换筛选条件或搜索关键词。':'选择一个 Agent，自动选题并开始评测，完成后回来查看真实结果。',summary.jobs.length?'':start)}<p class="library-note">显示已加载的最近记录。不同题库、评分标准或评分量表的结果不直接合并比较。</p>`;
}
export function renderRun(job,result){
 const p=job.progress??{},run=result?.run,allCases=new Map((p.cases??[]).map(c=>[c.caseId,{id:c.caseId,title:c.caseId,status:c.phase??c.status}]));
 for(const c of run?.cases??[])allCases.set(c.id,{...allCases.get(c.id),...c});
 const links=(result?.reportPaths??[]).map(reportHref).filter(Boolean);
 const completed=p.ended??0,total=p.total??run?.planned??0;
 return `<button class="back-link" data-reports-back>← 全部评测记录</button>`+heading(esc(jobName(job))+' 的评测',`${date(job.createdAt)} · ${esc(job.runId)}`,isActive(job)?`<button data-cancel="${esc(job.id)}" data-kind="${esc(job.agentKind||'dsh')}" ${job.state==='CANCELLING'?'disabled':''}>${job.state==='CANCELLING'?'正在取消…':'取消评测'}</button>`:'')+`<section class="run-overview"><div class="run-summary-line">${tag(job)}<span>${esc(job.evaluationConfig?.mode==='FULL'?'完整流程':'结果评测')}</span><span>${total?completed+' / '+total+' 题已结束':'题量尚未确定'}</span></div>${progress(job)}<div class="run-counts"><span>正常完成 <b>${p.normal??'—'}</b></span><span>异常 <b>${p.failed??'—'}</b></span><span>取消 <b>${p.cancelled??'—'}</b></span></div></section>${(run?.failureCodes??[]).length?`<div class="note">运行问题：${run.failureCodes.map(esc).join('、')}</div>`:''}<div class="section-heading"><h2>逐题结果</h2><span class="muted">保留原始评分量表</span></div>${allCases.size?[...allCases.values()].map(c=>{const scores=Object.entries(c.scores??{}),caseReport=links.find(link=>link.includes('/cases/'+encodeURIComponent(c.id)+'/'));
 return `<details class="result-case" data-preserve="result-${esc(job.id)}-${esc(c.id)}"><summary><strong>${esc(c.title||c.id)}</strong><span>${esc(phases[c.status]||c.status||'等待执行')} · ${esc(c.time||'—')}</span></summary><div class="result-case-body">${scores.length?`<div class="score-table">${scores.map(([id,s])=>{const scale=s.scale??run?.scoreScale;const numeric=s.state==='scored'&&Number.isFinite(s.value);return `<div><strong>${esc(run?.labelNames?.[id]||labelName(id))}</strong><b>${numeric?`${s.value}${scale?.max?' / '+scale.max:''}`:s.state==='error'?'评分失败':'证据不足'}</b><p>${esc(s.reason||'暂无评分说明')}</p></div>`;}).join('')}</div>`:'<p class="muted">尚无有效评分。执行和评分进度以当前任务状态为准。</p>'}${c.finalAnswer?`<h3>最终回答</h3><pre>${esc(c.finalAnswer.slice(0,12000))}</pre>${c.answerTruncated||c.finalAnswer.length>12000?'<p class="muted">此处为截断预览，完整内容见报告。</p>':''}`:''}${caseReport?`<a class="text-link" href="${esc(caseReport)}" target="_blank" rel="noopener">打开单题报告 ↗</a>`:''}</div></details>`;}).join(''):empty(isActive(job)?'正在准备题目':'暂无单题结果',isActive(job)?'完成选题后，进度会自动显示在这里。':'检查运行日志了解是否在执行前失败。')}<details class="run-log" data-preserve="log-${esc(job.id)}"><summary>运行日志与诊断</summary><pre>${esc((job.events??[]).slice(-25).map(e=>`${date(e.time)} ${e.text??e.kind??''}`).join('\n')||'暂无日志。')}</pre></details>${links.length?`<div class="report-links"><h3>已归档报告</h3>${links.map((link,i)=>`<a href="${esc(link)}" target="_blank" rel="noopener">${link.includes('/cases/')?'单题报告 '+(i+1):'完整报告'} ↗</a>`).join('')}</div>`:''}`;
}
